const cardDets = [
  {
    img: "/public/hero.jpg",
    title: "How To Participate",
    text: `Think you have what it takes to be the next beauty queen? Register
            now and seize the opportunity to step into the world of glitz and
            glamour.`,
    btntext: "I want to Register",
  },
  {
    img: "/public/hero.jpg",
    title: "Want to vote?",
    text: `Think you have what it takes to be the next beauty queen? Register
            now and seize the opportunity to step into the world of glitz and
            glamour.`,
    btntext: "Create myVoting Account",
    btntext2: "See Contestants",
  },
];

export const eventDets = [
  {
    img: "/public/hero.jpg",
    title: "Grand Prize",
    text: `A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.`,
  },
  {
    img: "/public/hero.jpg",
    title: "First Runner Up",
    text: `A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.`,
  },
  {
    img: "/public/hero.jpg",
    title: "Second Runner Up",
    text: `A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.`,
  },
];

export const galContestants = [
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "",
    id: "8h89",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "",
    id: "s934",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "tall",
    id: "ci388",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "wide",
    id: "sai29",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "",
    id: "dsn8",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "tall",
    id: "nds8",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "tall",
    id: "d828s",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "",
    id: "381hd",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "wide",
    id: "da923",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "wide",
    id: "bz98w9",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "wide",
    id: "hd88U",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "tall",
    id: "sa8h2",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "",
    id: "skmsi9",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "",
    id: "ds89382",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "",
    id: "dinss8h345",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "",
    id: "dnsw4rn48",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "wide",
    id: "bnd284",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "",
    id: "nfidi983",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "",
    id: "1mks339",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "",
    id: "8sh4b89j",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "wide",
    id: "ljk092s8",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "wide",
    id: "jsi2n&2",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "big",
    id: "nf9393",
  },
  {
    img: "/public/hero.jpg",
    name: "Kane",
    bio: "A stunning diamond tiara and a fully sponsored luxury vacation to a private island retreat.",
    age: "25",
    country: "USA",
    cn: "",
    id: "fhfs383",
  },
];

export default cardDets;
